# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:00
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('lang', models.CharField(max_length=225, verbose_name='Language')),
                ('popRank', models.CharField(blank=True, max_length=225, null=True)),
                ('woeid', models.CharField(max_length=225, verbose_name='Where on Earth ID')),
                ('uri', models.CharField(blank=True, max_length=225, null=True, verbose_name='URI')),
                ('admin1_content', models.CharField(blank=True, max_length=225, null=True)),
                ('admin1_woeid', models.CharField(blank=True, max_length=225, null=True)),
                ('admin1_type', models.CharField(blank=True, max_length=225, null=True)),
                ('admin2_content', models.CharField(blank=True, max_length=225, null=True)),
                ('admin2_woeid', models.CharField(blank=True, max_length=225, null=True)),
                ('admin2_type', models.CharField(blank=True, max_length=225, null=True)),
                ('admin3_content', models.CharField(blank=True, max_length=225, null=True)),
                ('admin3_woeid', models.CharField(blank=True, max_length=225, null=True)),
                ('admin3_type', models.CharField(blank=True, max_length=225, null=True)),
                ('latitude', models.CharField(blank=True, max_length=225, null=True)),
                ('longitude', models.CharField(blank=True, max_length=225, null=True)),
                ('locality_content', models.CharField(blank=True, max_length=225, null=True)),
                ('locality_woeid', models.CharField(blank=True, max_length=225, null=True)),
                ('locality_type', models.CharField(blank=True, max_length=225, null=True)),
                ('country_content', models.CharField(blank=True, max_length=225, null=True)),
                ('country_woeid', models.CharField(blank=True, max_length=225, null=True)),
                ('country_code', models.CharField(blank=True, max_length=225, null=True)),
                ('country_type', models.CharField(blank=True, max_length=225, null=True)),
                ('northEast_latitude', models.CharField(blank=True, max_length=225, null=True)),
                ('northEast_longitude', models.CharField(blank=True, max_length=225, null=True)),
                ('southWest_latitude', models.CharField(blank=True, max_length=225, null=True)),
                ('southWest_longitude', models.CharField(blank=True, max_length=225, null=True)),
                ('sysname', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=255, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225, verbose_name='Title')),
                ('pressure', models.CharField(blank=True, max_length=225, null=True)),
                ('rising', models.CharField(blank=True, max_length=225, null=True)),
                ('visibility', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='visibility (km)')),
                ('humidity', models.IntegerField(verbose_name='humidity (%)')),
                ('date', models.CharField(blank=True, max_length=225, null=True)),
                ('text', models.CharField(blank=True, max_length=225, null=True)),
                ('temp', models.IntegerField(verbose_name='temperature')),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('region', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, max_length=225, null=True)),
                ('sunset', models.CharField(blank=True, max_length=225, null=True)),
                ('sunrise', models.CharField(blank=True, max_length=225, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=225, null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='wind speed (km/h)')),
                ('wind_chill', models.CharField(blank=True, max_length=225, null=True)),
                ('forecast', jsonfield.fields.JSONField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.Location', verbose_name='City Location')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Weather log',
                'verbose_name_plural': 'Weather logs',
            },
        ),
    ]
